spring:
  datasource:
    url: jdbc:mysql://rm-2zel2q0w4x1t6sn77ko.mysql.rds.aliyuncs.com:3306/spring_demo
    username: yuanenzhi
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver