version: '3'
networks:
  default:
    external:
      name: spring
services:
  admin-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: admin-server
    container_name: admin-server
    hostname: admin-server
    ports:
    - 9080:8081
