spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: yuanenzhi
    password: Root@123
    url: jdbc:mysql://rm-2zel2q0w4x1t6sn77ko.mysql.rds.aliyuncs.com:3306/spring_demo
  cache:
    account:
      entry-ttl: 1h
    role:
      entry-ttl: 1h
    type: redis
    redis:
      key-prefix: cache
      time-to-live: 10s
  redis:
    host: 8.140.177.12
    password: root
#mybatis-plus:
#  mapper-locations: classpath*:mappers/*.xml
#mybatis:
#  mapper-locations: ${mybatis-plus.mapper-locations}