spring:
  datasource:
    url: jdbc:mysql://rm-2zel2q0w4x1t6sn77ko.mysql.rds.aliyuncs.com:3306/spring_demo
    username: yuanenzhi
    password: Root@123
  redis:
    host: 8.140.177.12
    password: root
  cache:
    type: redis
  data:
    mongodb:
      uri: mongodb:root:root@8.140.177.12/shower
management:
  endpoints:
    web:
      exposure:
        include: '*'
