spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  cache:
    type: redis
    redis:
      key-prefix: cache
      time-to-live: 10m
  redis:
    host: ${SPRING_REDIS_HOST}
    password: ${SPRING_REDIS_PASSWORD}
    port: ${SPRING_REDIS_PORT}
  jackson:
    date-format: yyyy-MM-dd
    locale: zh_CN
logging:
  level:
    web: debug
