spring:
  profiles:
#    include: docker2
    include: commons
#    include: docker
server:
  servlet:
    encoding:
      force-response: true
      force-request: true
      force: true
      charset: UTF-8