version: '3'
networks:
  default:
    external:
      name: spring
services:
  admin1:
    build:
      context: ./admin1
      dockerfile: Dockerfile
    image: admin1
    container_name: admin1
    hostname: admin1
    expose:
      - 8080
    ports:
      - 8181:8080
  admin2:
    build:
      context: ./admin2
      dockerfile: Dockerfile
    image: admin2
    container_name: admin2
    hostname: admin2
    expose:
      - 8080
    ports:
      - 8182:8080
  adminasync1:
    build:
      context: ./adminasync1
      dockerfile: Dockerfile
    image: adminasync1
    container_name: adminasync1
    hostname: adminasync1
    expose:
      - 8080
    ports:
      - 8281:8080
  adminasync2:
    build:
      context: ./adminasync2
      dockerfile: Dockerfile
    image: adminasync2
    container_name: adminasync2
    hostname: adminasync2
    expose:
      - 8080
    ports:
      - 8282:8080
  adminrx1:
    build:
      context: ./adminrx1
      dockerfile: Dockerfile
    image: adminrx1
    container_name: adminrx1
    hostname: adminrx1
    expose:
      - 8080
    ports:
      - 8381:8080
  adminrx2:
    build:
      context: ./adminrx2
      dockerfile: Dockerfile
    image: adminrx2
    container_name: adminrx2
    hostname: adminrx2
    expose:
      - 8080
    ports:
      - 8382:8080
