version: '3'
networks:
  default:
    external:
      name: spring
services:
  admin1:
    build:
      context: ./admin1
      dockerfile: Dockerfile
    image: admin1
    container_name: admin1
    hostname: admin1
    expose:
      - 8080
    ports:
      - 8181:8080
  admin2:
    build:
      context: ./admin2
      dockerfile: Dockerfile
    image: admin2
    container_name: admin2
    hostname: admin2
    expose:
      - 8080
    ports:
      - 8182:8080
  adminasync1:
    build:
      context: ./adminasync1
      dockerfile: Dockerfile
    image: adminasync1
    container_name: adminasync1
    hostname: adminasync1
    expose:
      - 8080
    ports:
      - 8281:8080
  adminasync2:
    build:
      context: ./adminasync2
      dockerfile: Dockerfile
    image: adminasync2
    container_name: adminasync2
    hostname: adminasync2
    expose:
      - 8080
    ports:
      - 8282:8080
  adminrx1:
    build:
      context: ./adminrx1
      dockerfile: Dockerfile
    image: adminrx1
    container_name: adminrx1
    hostname: adminrx1
    expose:
      - 8080
    ports:
      - 8381:8080
  adminrx2:
    build:
      context: ./adminrx2
      dockerfile: Dockerfile
    image: adminrx2
    container_name: adminrx2
    hostname: adminrx2
    expose:
      - 8080
    ports:
      - 8382:8080
  mysql1:
    build:
      context: ./mysql1
      dockerfile: Dockerfile
    image: mysql1
    container_name: mysql1
    hostname: mysql1
    expose:
      - 8080
    ports:
    - 8481:8080
  mysql2:
    build:
      context: ./mysql2
      dockerfile: Dockerfile
    image: mysql2
    container_name: mysql2
    hostname: mysql2
    expose:
      - 8080
    ports:
      - 8482:8080
  mysqlasync1:
    build:
      context: ./mysqlasync1
      dockerfile: Dockerfile
    image: mysqlasync1
    container_name: mysqlasync1
    hostname: mysqlasync1
    expose:
      - 8080
    ports:
      - 8581:8080
  mysqlasync2:
    build:
      context: ./mysqlasync2
      dockerfile: Dockerfile
    image: mysqlasync2
    container_name: mysqlasync2
    hostname: mysqlasync2
    expose:
      - 8080
    ports:
      - 8582:8080
  mysqlrx1:
    build:
      context: ./mysqlrx1
      dockerfile: Dockerfile
    image: mysqlrx1
    container_name: mysqlrx1
    hostname: mysqlrx1
    expose:
      - 8080
    ports:
      - 8681:8080
    mysqlrx2:
      build:
        context: ./mysqlrx2
        dockerfile: Dockerfile
      image: mysqlrx2
      container_name: mysqlrx2
      hostname: mysqlrx2
      expose:
        - 8080
      ports:
        - 8682:8080